name: vue-minesweeper

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build

      - name: Copy files to the server
        uses: appleboy/scp-action@master
        with:
          host: 111.229.120.98
          username: root
          key: ${{ secrets.KILIG }}
          port: 22
          source: 'dist/*'
          target: '~/web'

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: 111.229.120.98
          username: root
          key: ${{ secrets.KILIG }}
          port: 22
          script: |
            cd ~/web/vue-minesweeper
            pnpm run restart
